AWSTemplateFormatVersion: 2010-09-09
Description: "SO9250 Guidance for Natural Language Queries of Relational Databases on AWS - ECS for OpenAI stack template."
Parameters:
  OpenAIModelName:
    Type: String
    Default: "gpt-4"
    Description: The OpenAI LLM to call via their API.

  ECRImageTag:
    Type: String
    Default: "2.0.0-oai"
    Description: The name of the ECR Image tag to use with ECS/Fargate.

  TaskName:
    Type: String
    Default: "nlq-genai-oai"
    Description: The name of the ECS Task and Fargate Service.

  ProjectTagValue:
    Type: String
    Default: "SO9250 Guidance for Natural Language Queries of Relational Databases on AWS"
    Description: The Project Tag value applied to all resources.

Resources:
  ECSTaskDefinitionOpenAI:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      ContainerDefinitions:
        - Environment:
            - Name: "REGION_NAME"
              Value: !Ref AWS::Region
            - Name: "MODEL_NAME"
              Value: !Ref OpenAIModelName
            - Name: "OPENAI_API_KEY"
              Value: "{{resolve:secretsmanager:/nlq/OpenAIAPIKey}}"
          Essential: true
          Image: !Sub "{{resolve:ssm:/nlq/ECRRepositoryUri}}:${ECRImageTag}"
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              awslogs-create-group: "true"
              awslogs-group: "{{resolve:ssm:/nlq/ECSLogGroupName}}"
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: "ecs"
          Name: !Ref TaskName
          PortMappings:
            - ContainerPort: "{{resolve:ssm:/nlq/NLQAppPort}}"
              HostPort: "{{resolve:ssm:/nlq/NLQAppPort}}"
              Protocol: "tcp"
      Family: !Ref TaskName
      TaskRoleArn: "{{resolve:ssm:/nlq/EcsTaskExecutionRoleArn}}"
      ExecutionRoleArn: "{{resolve:ssm:/nlq/EcsTaskExecutionRoleArn}}"
      NetworkMode: "awsvpc"
      RequiresCompatibilities:
        - "FARGATE"
      Cpu: "1024"
      Memory: "3072"
      Tags:
        - Key: "Project"
          Value: !Ref ProjectTagValue

  ECSServiceOpenAI:
    Type: "AWS::ECS::Service"
    Properties:
      ServiceName: !Ref TaskName
      Cluster: "{{resolve:ssm:/nlq/ECSClusterArn}}"
      LoadBalancers:
        - TargetGroupArn: "{{resolve:ssm:/nlq/TargetGroupTargetGroupArn}}"
          ContainerName: !Ref TaskName
          ContainerPort: "{{resolve:ssm:/nlq/NLQAppPort}}"
      DesiredCount: 1
      LaunchType: "FARGATE"
      PlatformVersion: "LATEST"
      TaskDefinition: !Ref ECSTaskDefinitionOpenAI
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: "ENABLED"
          SecurityGroups:
            - "{{resolve:ssm:/nlq/ECSSecurityGroupGroupId}}"
            - "{{resolve:ssm:/nlq/VPCDefaultSecurityGroup}}"
          Subnets:
            - "{{resolve:ssm:/nlq/PublicSubnet1SubnetId}}"
            - "{{resolve:ssm:/nlq/PublicSubnet2SubnetId}}"
      HealthCheckGracePeriodSeconds: 60
      SchedulingStrategy: "REPLICA"
      DeploymentController:
        Type: "ECS"
      Tags:
        - Key: "Project"
          Value: !Ref ProjectTagValue
