# Natural Language Query (NLQ) demo using Amazon RDS for PostgreSQL and Amazon Bedrock.
# Author: Gary A. Stafford (garystaf@amazon.com)
# Date: 2023-08-12

FROM python:3.11.4-slim

LABEL name="nlq-genai" \
    version="1.0.0-bedrock" \
    maintainer="Gary A. Stafford (garystaf@amazon.com)"

ENV PIP_DEFAULT_TIMEOUT=100 \
    # allow statements and log messages to immediately appear
    PYTHONUNBUFFERED=1 \
    # disable a pip version check to reduce run-time & log-spam
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    # cache is useless in docker image, so disable to reduce image size
    PIP_NO_CACHE_DIR=1

COPY requirements_bedrock.txt .
# Bedrock requires specific AWS packages during preview/pre-GA period
# see the Amazon Bedrock User Guide for access to the latest versions
COPY awscli-1.29.21-py3-none-any.whl .
COPY boto3-1.28.21-py3-none-any.whl .
COPY botocore-1.31.21-py3-none-any.whl .

RUN set -ex \
    # create a non-root user
    && groupadd --system --gid 1001 appgroup \
    && useradd --system --uid 1001 --gid 1001 --create-home appuser \
    # upgrade the package index and install security upgrades
    && apt-get update \
    && apt-get upgrade -y \
    && apt-get install gcc g++ git make -y \
    # install dependencies
    && pip install -r requirements_bedrock.txt -U \
    # for the CLI or SDK with Amazon Bedrock
    && pip install botocore-1.31.21-py3-none-any.whl \
    && pip install boto3-1.28.21-py3-none-any.whl \
    # optional, for the CLI with Amazon Bedrock:
    && pip install awscli-1.29.21-py3-none-any.whl \
    # clean up
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /home/appuser/

# copy required files to image
COPY --chown=appuser:appgroup static static
COPY --chown=appuser:appgroup moma_examples.yaml .
COPY --chown=appuser:appgroup app_bedrock.py streamlit_app.py

# set streamlit config via env vars
ENV STREAMLIT_SERVER_ENABLE_STATIC_SERVING=true
ENV STREAMLIT_SERVER_PORT=8501
ENV STREAMLIT_LOGGER_LEVEL="info"
ENV STREAMLIT_CLIENT_TOOLBAR_MODE="viewer"
ENV STREAMLIT_CLIENT_SHOW_ERROR_DETAILS=false
ENV STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
ENV STREAMLIT_THEME_BASE="light"
ENV STREAMLIT_THEME_PRIMARY_COLOR="#3383f6"

EXPOSE 8501

CMD [ "streamlit", "run", "streamlit_app.py"]

# set the user to run the application
USER appuser